In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
x = np.array([1e7, 1e8, 2e5, 2e7])
print(x)
y = np.exp(x) / sum(np.exp(x))
print("上溢：", y)
x = x - np.max(x)
print(x)
y = np.exp(x)/sum(np.exp(x))
print("上溢处理：", y)

[1.e+07 1.e+08 2.e+05 2.e+07]
上溢： [nan nan nan nan]
[-90000000.         0. -99800000. -80000000.]
上溢处理： [0. 1. 0. 0.]


<ipython-input-2-0667fec1ac9e>:3: RuntimeWarning: overflow encountered in exp
  y = np.exp(x) / sum(np.exp(x))
<ipython-input-2-0667fec1ac9e>:3: RuntimeWarning: invalid value encountered in true_divide
  y = np.exp(x) / sum(np.exp(x))


In [3]:
x = np.array([-1e10, -1e9, -2e10, -1e10])
y = np.exp(x)/sum(np.exp(x))
print("下溢：", y)
x = x - np.max(x)
print(x)
y = np.exp(x)/sum(np.exp(x))
print("下溢处理：", y)
print("log softmax(x):", np.log(y))
# 对 log softmax 下溢的处理：
def logsoftmax(x):
    print('x:', x)
    print('sum:', sum(np.exp(x)))
    y = x - np.log(sum(np.exp(x)))
    return y
print("logsoftmax(x):", logsoftmax(x))

下溢： [nan nan nan nan]
[-9.0e+09  0.0e+00 -1.9e+10 -9.0e+09]
下溢处理： [0. 1. 0. 0.]
log softmax(x): [-inf   0. -inf -inf]
x: [-9.0e+09  0.0e+00 -1.9e+10 -9.0e+09]
sum: 1.0
logsoftmax(x): [-9.0e+09  0.0e+00 -1.9e+10 -9.0e+09]


<ipython-input-3-ce2cc2aa1b6a>:2: RuntimeWarning: invalid value encountered in true_divide
  y = np.exp(x)/sum(np.exp(x))
<ipython-input-3-ce2cc2aa1b6a>:8: RuntimeWarning: divide by zero encountered in log
  print("log softmax(x):", np.log(y))


In [4]:
x0 = np.array([1.0, 1.0, 1.0])
A = np.array([[1.0, -2.0, 1.0], [0.0, 2.0, -8.0], [-4.0, 5.0, 9.0]])
b = np.array([0.0, 8.0, -9.0])
epsilon = 0.001
delta = 1e-3

In [9]:
"""
gradient descent
"""
def matmul_chain(*args):
    if len(args) == 0: return np.nan
    result = args[0]
    for x in args[1:]:
        result = result @ x
    return result

def gradient_decent(x, A, b, epsilon, delta):
    while la.norm(matmul_chain(A.T, A, x) - matmul_chain(A.T, b)) > delta:
        x -= epsilon * (matmul_chain(A.T, A, x) - matmul_chain(A.T, b))
    return x

gradient_decent(x0, A, b, epsilon, delta)

array([27.82277014, 15.34731055,  2.83848939])

In [12]:
"""
newton
"""
def matmul_chain(*args):
    if len(args) == 0: return np.nan
    result = args[0]
    for x in args[1:]:
        result = result @ x
    return result

def newton(x, A, b):
    x = matmul_chain(np.linalg.inv(matmul_chain(A.T, A)), A.T, b)
    return x
newton(x0, A, b)

array([29., 16.,  3.])

In [14]:
"""
constrain optimazation
"""
def matmul_chain(*args):
    if len(args) == 0: return np.nan
    result = args[0]
    for x in args[1:]:
        result = result @ x
    return result

def contrain_opti(x, A, b, delta):
    k = len(x)
    lamb = 0
    while np.abs(np.dot(x.T, x) - 1) > 5e-2:
        x = matmul_chain(np.linalg.inv(matmul_chain(A.T, A) + 2 * lamb * np.identity(k)), A.T, b)
        lamb += np.dot(x.T, x) - 1
    return x

contrain_opti(x0, A, b, delta)

array([ 0.23637902,  0.05135858, -0.94463626])

In [16]:
import numpy
print("numpy:", numpy.__version__)

numpy: 1.19.2
