In [4]:
import numpy as np
import numpy.linalg as la

In [10]:
x = np.array([1e7, 1e8, 2e5, 2e7])
print(x)
y = np.exp(x) / sum(np.exp(x))
print("上溢：", y)
x = x - np.max(x)
print(x)
y = np.exp(x)/sum(np.exp(x))
print("上溢处理：", y)

[1.e+07 1.e+08 2.e+05 2.e+07]
上溢： [nan nan nan nan]
[-90000000.         0. -99800000. -80000000.]
上溢处理： [0. 1. 0. 0.]


<ipython-input-10-0667fec1ac9e>:3: RuntimeWarning: overflow encountered in exp
  y = np.exp(x) / sum(np.exp(x))
<ipython-input-10-0667fec1ac9e>:3: RuntimeWarning: invalid value encountered in true_divide
  y = np.exp(x) / sum(np.exp(x))


In [22]:
x = np.array([-1e10, -1e9, -2e10, -1e10])
y = np.exp(x)/sum(np.exp(x))
print("下溢：", y)
x = x - np.max(x)
print(x)
y = np.exp(x)/sum(np.exp(x))
print("下溢处理：", y)
print("log softmax(x):", np.log(y))
# 对 log softmax 下溢的处理：
def logsoftmax(x):
    print('x:', x)
    print('sum:', sum(np.exp(x)))
    y = x - np.log(sum(np.exp(x)))
    return y
print("logsoftmax(x):", logsoftmax(x))

下溢： [nan nan nan nan]
[-9.0e+09  0.0e+00 -1.9e+10 -9.0e+09]
下溢处理： [0. 1. 0. 0.]
log softmax(x): [-inf   0. -inf -inf]
x: [-9.0e+09  0.0e+00 -1.9e+10 -9.0e+09]
sum: 1.0
logsoftmax(x): [-9.0e+09  0.0e+00 -1.9e+10 -9.0e+09]


<ipython-input-22-ce2cc2aa1b6a>:2: RuntimeWarning: invalid value encountered in true_divide
  y = np.exp(x)/sum(np.exp(x))
<ipython-input-22-ce2cc2aa1b6a>:8: RuntimeWarning: divide by zero encountered in log
  print("log softmax(x):", np.log(y))
